# Generated by Django 2.2.3 on 2019-07-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skolr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
