# Generated by Django 2.2.3 on 2019-07-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skolr', '0004_teacher_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
