# Generated by Django 2.2.3 on 2019-07-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skolr', '0005_department_hod'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_year', models.IntegerField()),
                ('to_year', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
