# Generated by Django 2.2.3 on 2019-07-08 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skolr', '0006_academicyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skolr.AcademicYear'),
            preserve_default=False,
        ),
    ]
